# Generated by Django 2.2.6 on 2019-10-27 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesos',
            fields=[
                ('id_accesos', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'accesos',
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id_apoderado', models.IntegerField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'apoderado',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('pabellon', models.CharField(max_length=10)),
                ('capacidad', models.CharField(max_length=10)),
                ('n_habitacion', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'habitacion',
            },
        ),
        migrations.CreateModel(
            name='InternoPeriodo',
            fields=[
                ('id_interno_periodo', models.IntegerField(primary_key=True, serialize=False)),
                ('id_apoderado', models.ForeignKey(db_column='id_apoderado', on_delete=django.db.models.deletion.CASCADE, to='permisos.Apoderado')),
            ],
            options={
                'db_table': 'interno_periodo',
            },
        ),
        migrations.CreateModel(
            name='InternoResidencia',
            fields=[
                ('id_interno_residencia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_residencia', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'interno_residencia',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('nombre_periodo', models.CharField(max_length=20)),
                ('fecha_fin', models.DateField()),
                ('estado', models.IntegerField()),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('dni', models.DecimalField(db_column='DNI', decimal_places=0, max_digits=8)),
                ('codigo', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('estado', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id_tipo_evento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_evento',
            },
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id_privilegio', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_privilegio', models.CharField(blank=True, max_length=20, null=True)),
                ('id_accesos', models.ForeignKey(db_column='id_accesos', on_delete=django.db.models.deletion.CASCADE, to='permisos.Accesos')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='permisos.Persona')),
            ],
            options={
                'db_table': 'privilegio',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.IntegerField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=50)),
                ('fecha_estimada_salida', models.DateField()),
                ('fecha_estimada_entrada', models.DateField()),
                ('lugar', models.CharField(max_length=30)),
                ('observaciones', models.CharField(max_length=50)),
                ('id_persona', models.CharField(max_length=20)),
                ('id_interno_periodo', models.ForeignKey(db_column='id_interno_periodo', on_delete=django.db.models.deletion.CASCADE, to='permisos.InternoPeriodo')),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='PeriodoUsuario',
            fields=[
                ('id_periodo_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, to='permisos.Periodo')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='permisos.Persona')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='permisos.Rol')),
            ],
            options={
                'db_table': 'periodo_usuario',
            },
        ),
        migrations.CreateModel(
            name='PeriodoHabitacion',
            fields=[
                ('id_periodo_habitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('id_habitacion', models.ForeignKey(db_column='id_habitacion', on_delete=django.db.models.deletion.CASCADE, to='permisos.Habitacion')),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, to='permisos.Periodo')),
            ],
            options={
                'db_table': 'periodo_habitacion',
            },
        ),
        migrations.AddField(
            model_name='internoperiodo',
            name='id_periodo',
            field=models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, to='permisos.Periodo'),
        ),
        migrations.AddField(
            model_name='internoperiodo',
            name='id_periodo_habitacion',
            field=models.ForeignKey(db_column='id_periodo_habitacion', on_delete=django.db.models.deletion.CASCADE, to='permisos.PeriodoHabitacion'),
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_incidencia', models.DateField()),
                ('estado', models.IntegerField()),
                ('id_periodo_usuario', models.ForeignKey(db_column='id_periodo_usuario', on_delete=django.db.models.deletion.CASCADE, to='permisos.PeriodoUsuario')),
            ],
            options={
                'db_table': 'incidencia',
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='id_interno_residencia',
            field=models.ForeignKey(db_column='id_interno_residencia', on_delete=django.db.models.deletion.CASCADE, to='permisos.InternoResidencia'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.IntegerField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_periodo_usuario', models.ForeignKey(db_column='id_periodo_usuario', on_delete=django.db.models.deletion.CASCADE, to='permisos.PeriodoUsuario')),
                ('id_tipo_evento', models.ForeignKey(db_column='id_tipo_evento', on_delete=django.db.models.deletion.CASCADE, to='permisos.TipoEvento')),
            ],
            options={
                'db_table': 'evento',
            },
        ),
        migrations.CreateModel(
            name='EstadoPermiso',
            fields=[
                ('id_estado_permiso', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_operacion', models.DateField()),
                ('estado', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha_salida', models.DateField()),
                ('fecha_entrada', models.DateField()),
                ('falta_postpermiso', models.CharField(max_length=30)),
                ('id_periodo_usuario', models.ForeignKey(db_column='id_periodo_usuario', on_delete=django.db.models.deletion.CASCADE, to='permisos.PeriodoUsuario')),
                ('id_permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, to='permisos.Permiso')),
            ],
            options={
                'db_table': 'estado_permiso',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEvento',
            fields=[
                ('id_reporte_evento', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, to='permisos.Evento')),
                ('id_interno_periodo', models.ForeignKey(db_column='id_interno_periodo', on_delete=django.db.models.deletion.CASCADE, to='permisos.InternoPeriodo')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='permisos.Persona')),
            ],
            options={
                'db_table': 'asistencia_evento',
            },
        ),
    ]
