# Generated by Django 2.2.6 on 2019-10-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesos',
            name='id_accesos',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='id_apoderado',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
